### ISSUE TITLE
Create a dedicated page with Vue guidelines

### ISSUE THREAD

**Issue by freekmurze** [spatie/guidelines.spatie.be#28]
Possible subjects:

- structure of vue file (proposal, `template`, `script`, `style`
- formatting use of subcomponents in templates (already in JS guidelines)
- naming of subcomponents (proposal: kebab-cased, eg `input-field`
- naming of events (proposal: image `on` being prefix but don't actually add it, eg `change`)
- order of components (proposal: alphabetical)
- prop order on subcomponents (proposal: `v-statements` first, than props, than event handlers
- order of the basic parts of a component (proposal: `props`  `computed`, `data`, `mixins`, `components`, `created`,  `mounted`, `methods`)
- order of the `imports` (proposal: alphabetical)

**Comment by sebastiandedeyne** [comment]
Counterproposal 🙈 

1. Mixins
2. Props
3. Components
4. Data
5. Lifecycle methods
6. Watchers
7. Computed
8. Methods

Import order: Tbh I've given up on that in JS.

```
import 'foobar';
import Foo from 'foobar';
import * as Foo from 'foobar';
import { Foo } from 'foobar';
```

**Comment by freekmurze** [comment]
New suggestion on order as discussed. The first three are probably the ones you'll likely want to see when quickly glancing at a component you're not familiar with.

Components are last because you'll likely to see the used subcomponents when viewing the template in a vue file.

1. Mixins
2. Props
3. Data
4. Lifecycle methods
5. Watchers
6. Computed
7. Methods
8. Components

**Comment by rathesDot** [comment]
In the [Vue Documentation](https://vuejs.org/v2/guide/components.html#Registration) you find this:

> Note that Vue does not enforce the W3C rules for custom tag names (all-lowercase, must contain a hyphen) though following this convention is considered good practice.

So for `naming of subcomponents` I would add the rule that components should have at least one hyphen.

---

For the order of the component parts, it's quite interesting to see that you have component at the last position.

I do use the following order:

Mixins
Props
Data
Computed
Components
Lifecycle methods
Watchers
Methods

Especially I prefer to have data/computed together as they are both some kind of data. So if I look up some var in the data field, but don't find it, the next step would be to go for the computed props ...

**Comment by sebastiandedeyne** [comment]
> So for naming of subcomponents I would add the rule that components should have at least one hyphen

If you're writing Vue templates that are getting compiled before entering the browser, this doesn't really matter. I'm not a fan of the hyphen rule because it forces you to use oddly verbose component names when it isn't always necessary.

**Comment by ratiw** [comment]
I usually go with the following structure

1. Mixins -- external resource as an extension to the component itself
2. Components -- external resource as required dependency
3. Props -- properties which the component depend upon
4. Data -- internal data 
5. Computed -- computed set of data (relate to data)
6. Watchers -- react on the change of data (also relate to data)
7. Lifecycle methods
8. Methods

**Comment by arvanoid** [comment]
props, data and computed should be grouped together. It is all data after all. I also think components are similar to import/use in a class and therefore should be stay on top.

**Comment by sebastiandedeyne** [comment]
Close this since Vue has their own now?

**Comment by freekmurze** [comment]
Yup
